apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/christopherpinette5/managed-argocd-lab'
    path: portal
    targetRevision: HEAD
  destination:
    namespace: portal
    name: staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
